court_booking/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import home, partial_res, index, my_reservations, item_delete_view
from django.views.generic import TemplateView

app_name = 'court_booking' # za url putanju do appa


urlpatterns = [
     path('index/', index , name='index'),
     path('fullcalendar/', TemplateView.as_view(template_name="fullcalendar.html"), name='fullcalendar'),
     path('book/home/', home , name='home'),
     path('book/home/<int:month>/<int:day>/', home , name='home'),
     path('book/partial_res/', partial_res , name='partial_res'),
     path('my_reservations/', my_reservations , name='my_reservations'),
     #path('delete_res/<int:pk>/', delete_res , name='delete_res'),
     path('delete_mod/<int:pk>/', item_delete_view , name='item_delete_view')
     ]

django_court_booking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('schedule/', include('schedule.urls')),
    path('', include('court_booking.urls')),
]

court_booking/models.py
from django.db import models
from django.conf import settings
# Create your models here.
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


#Profile is used to extend user attributes because with allauth we only have basic attributes like first, last name
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True, on_delete=models.CASCADE)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Court(models.Model):
    court_name = models.CharField(max_length=200)

    def __str__(self):
        return self.court_name

class Reservation(models.Model):
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    end_time = models.TimeField(auto_now=False, auto_now_add=False)
    booking_date = models.DateField(auto_now=False, auto_now_add=False)
    court = models.ForeignKey(Court, on_delete=models.CASCADE, related_name='court_reservation')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_reservation')

court_booking/forms.py
from django import forms
from django.forms import ModelForm
from .models import Court, Reservation, Profile
from django.forms.widgets import TimeInput

# class TimePickerInput(forms.TimeInput):
#         input_type = 'time'

import datetime as dt
import time

HOUR_CHOICES = [(dt.time(hour=x, minute=m), '{:02d}:{:02d}'.format(x, m))
                for x in range(9, 20) for m in (0, 30)]
# HOUR_CHOICES = [time(h, m).strftime('%H:%M')
#                 for h in range(9, 17) for m in (0, 30)]


class SignupForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'location', 'birth_date')

    def signup(self, request, user):
        # Save your user
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

        user.profile.location = self.cleaned_data['location']
        user.profile.birth_date = self.cleaned_data['birth_date']
        user.profile.save()


class CourtForm(forms.ModelForm):

    class Meta:
        model = Court
        fields = ('court_name',)


class ReservationForm(forms.ModelForm):
    #with required = False we can disable validation on field
    #court = forms.CharField(required=False)

    class Meta:
        
        model = Reservation
        fields = ('start_time', 'end_time', 'booking_date', 'court')
        widgets = {
            'start_time': forms.TimeInput(format='%H:%M'),
            # 'start_time': TimePickerInput(format='%H:%M'),
            'end_time': forms.Select(choices=HOUR_CHOICES),
            'booking_date': forms.DateInput(format='%d.%m.%Y'),
            #'court': forms.TextInput()
        }

court_booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required #for function based views
from django.contrib.auth.mixins import LoginRequiredMixin #for classed based views
from django.db.models import F #F() expressions are good for memory
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.db import transaction
from django.core.cache import cache

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Reservation, Court
from .forms import ReservationForm, SignupForm, CourtForm
import calendar
from calendar import HTMLCalendar
from datetime import date
from django.db.models import F
# Create your views here.

import json


def index(request):
    return render(request, 'court_booking/index.html', {})

@login_required(login_url='account_login')
#we need to set default arguments to go to current month and day
def home(request, month=date.today().month, day=date.today().day):
    data = dict()
    #used to get a list of  single field in model
    courts = list(Court.objects.values_list('court_name', flat=True))
    name = 'Pero'
    # year = date.today().year
    # month = date.today().month
    # cal = HTMLCalendar().formatmonth(year, month)

    # if request.method == 'POST':
    #     form = ReservationForm(request.POST)
    # else:
    #     form = ReservationForm()
    #data['html_form'] = render_to_string('court_booking/home.html', context, request)
    #return JsonResponse(data)
    book_date = list(Reservation.objects.filter(booking_date__day=day, booking_date__month=month).values('start_time', 'end_time', 'court__court_name'))
    md = [month, day]
    print(md)
    context = {'courts':courts,'name':name, 'book_date':book_date, 'md':md}
    return render(request, 'court_booking/home.html', context)

def partial_res(request):
    data = dict()
    if request.method == 'POST':
        # court_nam = request.POST.get('court')
        # print(court_nam)
        # court = Court.objects.get(court_name=court_nam)
        # print(court)
        form = ReservationForm(request.POST)
        #if form.is_valid():
        print('ndjanddsknsf')
        res = form.save(commit=False)
        print(res)
        res.user = request.user
        res.save()
        data['html_form'] = render_to_string('court_booking/partial_reservation_form.html', {'form': form}, request)

    else:
        form = ReservationForm()
    context = {'form':form}
    data['html_form'] = render_to_string('court_booking/partial_reservation_form.html', context, request)
    return JsonResponse(data)


@login_required(login_url='account_login')
def my_reservations(request):
    reservations = Reservation.objects.filter(user=request.user, booking_date__day__gte=date.today().day, booking_date__month__gte=date.today().month)
    context = {'reservations': reservations}
    return render(request, 'court_booking/my_reservations.html', context)

#without modal
# def delete_res(request,pk):
#     res = Reservation.objects.get(id=pk)
#     if request.method == 'POST':
#         res.delete()
#         return redirect('court_booking:my_reservations')
#     return render(request, 'court_booking/delete.html', {'obj':res})


def partial_res(request):
    data = dict()
    if request.method == 'POST':
        # court_nam = request.POST.get('court')
        # print(court_nam)
        # court = Court.objects.get(court_name=court_nam)
        # print(court)
        form = ReservationForm(request.POST)
        #if form.is_valid():
        print('ndjanddsknsf')
        res = form.save(commit=False)
        print(res)
        res.user = request.user
        res.save()
        data['html_form'] = render_to_string('court_booking/partial_reservation_form.html', {'form': form}, request)

    else:
        form = ReservationForm()
    context = {'form':form}
    data['html_form'] = render_to_string('court_booking/partial_reservation_form.html', context, request)
    return JsonResponse(data)


def item_delete_view(request, pk):
    res = get_object_or_404(Reservation, id=pk)
    data = dict()
    if request.method == 'POST':
        res.delete()
        data['form_is_valid'] = True
        context = {'obj': res}
        messages.success(request, 'Item deleted!')
        data['html_form'] = render_to_string('court_booking/my_reservations.html',context, request)
    else:
        context = {'obj': res}
        data['html_form'] = render_to_string('court_booking/delete_modal.html', context, request)
    return JsonResponse(data)

court_booking/templates/court_booking/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Court Booking</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="keywords" content="court, court booking, sports" />
    <meta name="description" content="Book sport court" />
    <meta name="author" content="Dragan Manojlovic" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />

    <!-- CSS Libraries -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />


    <link rel="stylesheet" href="{% static 'css/easycal.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>

    <!-- Template Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    {% block head %} {% endblock %}

  </head>
  <body>
    {% block content %} {% endblock %}

    <!-- JavaScript Libraries -->

    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>

    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>
    <script src="{% static 'js/dataset.js' %}"></script>


<div id="cal-tab">

  {{ book_date |json_script:"reservation" }}
  {{ courts |json_script:"num_courts" }}
  <!-- safe way to include django variables to javascript -->
  <script type="text/javascript">var num_of_courts = JSON.parse(document.getElementById('num_courts').textContent);</script>
  <script type="text/javascript">var book_date = JSON.parse(document.getElementById('reservation').textContent);</script>
  <script src="{% static 'js/easycal.js' %}"></script>

  <script>

$(document).ready(function() {

      $('#calendar').datepicker({
       inline: true,
       firstDay: 1,
       showOtherMonths: true,
       minDate: 0,
       dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
       dateFormat: "dd-mm-yy",
       onSelect: function (date) {
         $( "ui-datepicker-week-end" ).on( "click", function() {
          alert("grgdggd")
          });
         var date = $(this).datepicker('getDate'),
            day  = date.getDate(),
            month = date.getMonth() + 1,
            year =  date.getFullYear();
            console.log(date)

            // $('.loaded').load("http://127.0.0.1:8000/book/home/" + month.toString() + "/" + day.toString() + "/")

            // $('.loaded').load("http://127.0.0.1:8000/book/home/" + month.toString() + "/" + day.toString() + "/"  ,function(data){
            //   console.log(data)
            //   var scripts = $(data).find("scripts");
            //
            // });


          //   $('.loaded').load("http://127.0.0.1:8000/book/home/" + month.toString() + "/" + day.toString() + "/" + " .mycal", function(responseText, textStatus, XMLHttpRequest) {
          //   $('.mycal').easycal();
          // })

          //To get the a reference to the div use .filter() if .find() is not working
          $.get("http://127.0.0.1:8000/book/home/" + month.toString() + "/" + day.toString() + "/",function(r){
            //console.log(els)
            var els = $(r).filter("#cal-tab")
            console.log(els);
            //$('.loaded').html('<div class="mycal" style="width: 100%"></div>"').append($(r).filter("#cal-tab"))
            $('.mycal').remove();
            $(r).filter(".mycal").insertAfter('#calendar');
            $('#cal-tab').remove();
            $(r).filter("#cal-tab").insertAfter(".loaded");
          
        });


       //      $( "#calendar" ).datepicker( { defaultDate: '+1m'} );
       //window.location="http://127.0.0.1:8000/book/home/" + month.toString() + "/" + day.toString() + "/"
      //date.toString() is now in dd-mm-yyyy format, change it to meet your requirements


        }

        
      });

      $(".mycal").easycal({
          
          timeFormat: "HH:mm",
          columnDateFormat: "dddd, DD MMM",
          minTime: "09:00",
          maxTime: "19:00",
          slotDuration: 30,
          dayClick: function (el, startTime) {
  
            //to get the closest td  of clicked element
            var md = {{md}}
            var court_name = $(el).closest('td').attr("data-courts");
            console.log(court_name)
            $.ajax({
              url: "/book/partial_res/",
              type: "get",
              dataType: "json",
              beforeSend: function () {
  
                if ($(el).next().css("background-color") == "rgb(255, 0, 0)") {
                  alert("1 hour is a minimum reservation")
                }
                else{
                $("#modal-book .modal-content").html("");
                $("#modal-book").modal("show");
                }
              },
              success: function (data) {
                $("#modal-book .modal-content").html(data.html_form);
  
                $("#id_start_time").val(startTime);
                document.getElementById('id_start_time').readOnly = true
  
                var fillEndTime = parseInt(startTime, 10) + 1 + ":" + startTime[3] + startTime[4] + ":00";
                $("#id_end_time").val(fillEndTime);
                //to remove dropdown options less than some value
                $('#id_end_time option').filter(function() {
                    return $(this).val() < fillEndTime;
                }).remove();
  
                //get today date
                var d = new Date();
                //var datestring = ("0" + d.getDate()).slice(-2) + "." + ("0" + (d.getMonth() + 1)).slice(-2) + "." + d.getFullYear();
                var datestring = ("0" + md[1]).slice(-2) + "." + ("0" + (md[0])).slice(-2) + "." + d.getFullYear();
                $("#id_booking_date").val(datestring);
  
                //to set selected field in dropdown
                $("#id_court option:contains("+court_name+")").prop('selected', true)
                //$("#id_court").prop('disabled', true)
                //$('#id_court option:not(:selected)').remove()
                //to disable click on dropdown
                $('#id_court').on('mousedown', function(e) {
                    e.preventDefault();
                    this.blur();
                    window.focus();
                  });
                  $('#id_court').css({'background-color': '#e9ecef', 'appearance':'none'});
              },
            });
  
            // $("#modal-timeslot").modal('show');
  
            // $('.ec-slot').click(function () {
            //   var name = $(this).closest('td').attr("data-date");
            //   console.log(name)
            //     //console.log($(this).data('time'));
            //     //Check to see if background color is set or if it's set to white.
            //     if(this.style.background == "" || this.style.background =="white") {
            //         $(this).css('background', 'red');
            //     }
            //     else {
            //         $(this).css('background', 'white');
            //     }
            // });
  
            console.log("Slot selected: " + startTime);
          },
          eventClick: function (eventId) {
            console.log("Event was clicked with id: " + eventId);
          },
  
          overlapColor: "#FF0",
          overlapTextColor: "#000",
          overlapTitle: "Multiple",
        });

});

    </script>

    <script type="text/javascript">
$(document).ready(function() {

      //iteration of array of dictionaries with jquery, setting the color to booked time
      $.each(book_date,function(index,value){
            $("td[data-courts='"+value.court__court_name+"']").find("div").each(function() {
                  if ( ($(this).attr('data-time') >= value.start_time.slice(0, -3)) && ($(this).attr('data-time') < value.end_time.slice(0, -3)) ) {
                    $(this).css({"background":"red", "pointer-events":"none"});
                    //$("div[data-time='"+$(this).attr('data-time')+"']").off()
                    //with $(this).off(); we disable click event
                    $(this).off();  
                  }
                });

      });

      // $(function(){
      //   $("div[data-time='09:30']").click(function(event) {
      //   alert('gooooo')
      // });
      // });

      //with off() we disable event handlers(click and other events)
      // $(function(){
      //   $("div[data-time='09:30']").off()
      // });

      $(function () {
        /* Functions */

        var loadForm = function () {
          console.log("loadtralala");
          var btn = $(this);
          $.ajax({
            url: btn.attr("data-url"),
            type: "get",
            dataType: "json",
            beforeSend: function () {
              $("#modal-book .modal-content").html("");
              $("#modal-book").modal("show");
            },
            success: function (data) {
              $("#modal-book .modal-content").html(data.html_form);
            },
          });
        };

        var saveForm = function () {
          console.log("savelalal");
          var form = $(this);
          $.ajax({
            url: form.attr("action"),
            data: form.serialize(),
            type: form.attr("method"),
            dataType: "json",
            success: function (data) {
              if (data.form_is_valid) {
                $("#izdano-table tbody").html(data.html_izdano_list);
                $("#modal-book").modal("hide");
                window.location.reload();
                //console.log(data.html_izdano_list)
              } else {
                $("#modal-book .modal-content").html(data.html_form);

                var start_time = $("#id_start_time").val();
                var end_time = $("#id_end_time option:selected").text();
                var court_name = $("#id_court option:selected").text();

                //for setting the occupied court by clicking on table column
                //pointer-events is used to make element unclickable
                $("td[data-courts='"+court_name+"']").find("div").each(function() {
                  if ( ($(this).attr('data-time') >= start_time) && ($(this).attr('data-time') < end_time) ) {
                    $(this).css({"background":"red", "pointer-events":"none"});
                  }
                });

                $("#modal-book").modal("hide");
              }
            },
          });
          return false;
        };

        /* Binding */

        // Create book
        $(".js-create-book").click(loadForm);
        $("#modal-book").off();
        $("#modal-book").on("submit", ".js-izdano-create-form", saveForm);

        // Update book
        $("#izdano-table").on("click", ".js-update-izdano", loadForm);
        $("#modal-book").on("submit", ".js-izdano-update-form", saveForm);

        // Delete book
        $(".cli").on("click", ".js-delete-load", loadForm);
        $("#modal-book").on("submit", ".js-delete-form", saveForm);
      });
    });

    </script>
  </div>

  <div class="loaded"></div>

    {% block javascript %}{% endblock %}
  </body>
</html>

court_booking/templates/court_booking/delete.html
<h1>Delete</h1>
<form action="" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>
    <input type="submit" value="Confirm" />
</form>

court_booking/templates/court_booking/delete_modal.html
{% load widget_tweaks %}

<form method="post" action="{% url 'court_booking:item_delete_view' obj.id %}" class="js-delete-form">
    {% csrf_token %}
    <div class="modal-header">
      <h4 class="modal-title">Cancel reservation</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <p class="lead">Are you sure you want to cancel the reservation?</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-danger">Cancel</button>
    </div>
  </form>

court_booking/templates/court_booking/home.html
{% extends 'court_booking/base.html' %} 
{% load static %}


{% block content %}

<div class="dis-flex">
<h2 class="head-login">Tennis Center</h2>

<div class="dropdown">
<p href="#" class="image-profile"><img class="image-size" src="{% static 'images/profile.png' %}" alt="" />
  <span>{{request.user}}</span>
  <i class="fa fa-angle-down"></i>
  <div class="dropdown-content">
    <a href="{% url 'court_booking:my_reservations' %}">My reservations</a>
    <a href="{% url 'account_logout' %}">Logout</a>
  </div>
</p>
</div>

</div>

<div id="calendar"></div>


<div class="mycal" style="width: 100%">
</div>

<div class="modal fade" id="modal-book">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

<!-- THE MODAL WE WILL BE USING -->
<!-- <div class="modal fade" id="modal-timeslot">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Potvrdi brisanje</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p class="lead">trrzr</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Zatvori</button>
              <button type="submit" class="btn btn-danger">Izbriši</button>
            </div>
        </div>
      </div>
     </div> -->
{% endblock %}

court_booking/templates/court_booking/index.html
{% load static %}

<!DOCTYPE HTML>
<!--
	Solid State by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Tennis Center</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	</head>
	<body>

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="{% url 'court_booking:index' %}">Tennis Center</a></h1>
						<nav>
							<a id="men" href="#menu">Menu</a>
						</nav>
					</header>


				<!-- Banner -->
					<section id="banner">
						<div class="inner">
							<div class="logo"><span class="icon"><img class="helpico" src="{% static 'images/tennis-ball.png' %}" alt=""></span></div>
							<h2>This is Tennis center</h2>
							<p><a href="{% url 'account_login' %}">Log in</a> to book and reserve tennis court</p>
							<p class="login"><a href="{% url 'account_login' %}" class="button">LOG IN</a></p>
						</div>
					</section>

				<!-- Wrapper -->
					<section id="wrapper">

						<!-- One -->
							<section id="one" class="wrapper spotlight style1">
								<div class="inner">
									<a href="#" class="image"><img src="{% static 'images/pic01.jpg' %}" alt="" /></a>
									<div class="content">
										<h2 class="major">Welcome to tennis center</h2>
										<p>To be able to book and reserve court you must register to our site.</p>
										<a href="{% url 'account_signup' %}" class="special">Register</a>
									</div>
								</div>
							</section>

					</section>

				<!-- Footer -->
					<section id="footer">
						<div class="inner">
							<h2 class="major">Get in touch</h2>
							<p>Cras mattis ante fermentum, malesuada neque vitae, eleifend erat. Phasellus non pulvinar erat. Fusce tincidunt, nisl eget mattis egestas, purus ipsum consequat orci, sit amet lobortis lorem lacus in tellus. Sed ac elementum arcu. Quisque placerat auctor laoreet.</p>
							<ul class="contact">
								<li class="icon solid fa-home">
									Untitled Inc<br />
									1234 Somewhere Road Suite #2894<br />
									Nashville, TN 00000-0000
								</li>
								<li class="icon solid fa-phone">(000) 000-0000</li>
								<li class="icon solid fa-envelope"><a href="#">information@untitled.tld</a></li>
								<li class="icon brands fa-twitter"><a href="#">twitter.com/untitled-tld</a></li>
								<li class="icon brands fa-facebook-f"><a href="#">facebook.com/untitled-tld</a></li>
								<li class="icon brands fa-instagram"><a href="#">instagram.com/untitled-tld</a></li>
							</ul>
							<ul class="copyright">
								<li>&copy; Untitled Inc. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</section>

			</div>

			<!-- Menu -->
			<nav id="menu">
				<div class="inner">
					<h2>Menu</h2>
					<ul class="links">
						<li><a href="{% url 'court_booking:index' %}">Home</a></li>
						<li><a href="{% url 'account_login' %}">Log In</a></li>
						<li><a href="{% url 'account_signup' %}">Register</a></li>
					</ul>
					<a href="#" class="close">Close</a>
				</div>
			</nav>

		<!-- Scripts -->
		<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
		<script src="{% static 'assets/js/main.js' %}"></script>
		

	</body>
</html>

court_booking/templates/court_booking/my_reservations.html
{% extends 'court_booking/base.html' %} 
{% load static %}

{% block content %}

<div class="modal fade" id="modal-book">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

<div class="dis-flex">
    <h2 class="head-login">Tennis Center</h2>
    
    <div class="dropdown">
    <p href="#" class="image-profile"><img class="image-size" src="{% static 'images/profile.png' %}" alt="" />
      <span>{{request.user}}</span>
      <i class="fa fa-angle-down"></i>
      <div class="dropdown-content">
        <a href="{% url 'court_booking:home' %}">Court booking</a>
        <a href="{% url 'account_logout' %}">Logout</a>
      </div>
    </p>
    </div>
    
</div>

<h2 style="text-align: center;">My reservations</h2>

<table class="res-page-table">
    <thead>
        <tr>
            <th>Court</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Date</th>
            <th>Cancel reservation</th>
        </tr>
    </thead>
    {% for res in reservations %}
    <tbody class="res-tbody-table">
        <tr>
            <td>{{res.court}}</td>
            <td>{{res.start_time|time:"H:i"}}</td>
            <td>{{res.end_time|time:"H:i"}}</td>
            <td>{{res.booking_date|date:"d.m.Y"}}</td>
            <td class="cli"> <button type="button"  data-url="{% url 'court_booking:item_delete_view' res.id %}" data-toggle="modal" class="js-delete-load but">Cancel</button></td>
        </tr>
    </tbody>
    {% endfor %}
</table>

{% endblock %}

court_booking/templates/court_booking/partial_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

court_booking/templates/court_booking/partial_reservation_form.html
{% load widget_tweaks %}

<form method="post" action="{% url 'court_booking:partial_res' %}" class="js-izdano-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Dodaj korisnika u bazu</h4>
     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
   <div class="modal-body">
     {% include 'court_booking/partial_form.html' %}
   </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Zatvori</button>
    <button type="submit" class="btn btn-primary">Dodaj korisnika</button>
  </div>
</form>